feat: add insights module
gadicc/node-yahoo-finance2 pull request #169
Opened 2021-05-08 20:47 UTC by PythonCreator27

Closes #168.

## Changes
- Add insights module
- Add tests

## TODO
 - [ ] add docs
 - [ ] see if tests pass or not

## Type
- [x] New Module
- [ ] Other New Feature
- [ ] Validation Fix
- [ ] Other Bugfix
- [ ] Docs
- [x] Chore/other

## Comments/notes
Currently, I cannot run tests locally, see https://github.com/gadicc/node-yahoo-finance2/pull/144#issuecomment-835503904. I am opening the PR early so that I can see CI run.

2021-05-09 08:21 UTC, gadicc commented
Hey @PythonCreator27, thanks so much, this is fantastic work as usual!  Thanks for yet another module!

I'm going to hold off merging a bit just until we solve the other issues, so we can have consistency on the `.js` extensions and just in case we end up reverting the esm stuff.

2021-05-13 21:09 UTC, PythonCreator27 commented
@gadicc Correct me if I am wrong, but now that the whole tests issue is sorted out, I think that this can be merged. The JSON imports should not matter, as any changes would only affect files that import JSON, which this module does not (directly).

2021-05-14 06:28 UTC, gadicc commented
Hey @PythonCreator27, you're absolutely right.  Sorry, slipped me mind with my upcoming trip.  Now that we know we're keeping ESM can I just ask that all the imports are on `.js` for consistency.  I'll tag them inline.  Thanks!  And of course, thanks again for contributing another awesome module!

2021-05-14 06:32 UTC, gadicc requested changes

2021-05-14 06:32 UTC, gadicc commented on src/modules/insights.spec.ts
> +import testYf from "../../tests/testYf";
here

2021-05-14 06:32 UTC, gadicc commented on src/other/quoteCombine.spec.ts
> +import testYf from "../../tests/testYf";
and here

2021-05-14 17:24 UTC, PythonCreator27 commented
Oops. Fixed now. Also generated json `http` files. @gadicc Anything else?

2021-05-15 08:23 UTC, gadicc commented
Awesome, @PythonCreator27, thanks!  I think maybe you didn't commit your fix on `quoteCombine.spec.ts` but it's such an easy fix that I'm going to merge and fix my end to avoid wasting any more time because of the timezone difference between us.  One last big final thanks from me for another module!

2021-05-15 08:23 UTC, merged

2021-06-01 05:13 UTC, gadicc commented
:tada: This PR is included in version 1.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/yahoo-finance2/v/1.11.0)
- [GitHub release](https://github.com/gadicc/node-yahoo-finance2/releases/tag/v1.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: